### ISSUE TITLE
In ProviderRepository.php line 208: Class 'LaravelEnso\VueDatatable\AppServiceProvider' not found

### ISSUE THREAD

**Issue by okedialf** [laravel-enso/Enso#200] opened 2019-02-15 12:30 UTC
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

Right after cloning and running composer install
### Steps to Reproduce

1. git clone
2. composer install

**Comment by jlsjonas** [comment] 2019-02-15 13:49
Just tested, can't reproduce using your steps.
What environment are you running on?

**Comment by okedialf** [comment] 2019-02-16 13:57
Apology for the template.  I resolved the issue by switching to 2.15.0.
Environment is Ubuntu Server 18.04.2 LTS PHP 7.2

**Comment by jlsjonas** [comment] 2019-02-18 12:43
Closing as the issue seems solved.

**Closed by jlsjonas** 2019-02-18 12:43 UTC
