### ISSUE TITLE
Preserve correct repo update order

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#130] opened 2018-08-21 12:37 UTC
This is  a **bug/workflow request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

When making breaking changes; ensure all sub-packages are updated before updating the Enso package.

I based myself on a new clone of Enso this morning and it seems that structuremanager isn't/wasn't updated yet to reflect the dt changes (getting missing route errors; although the routes are defined in the same way that worked last week while _playing around_

### Steps to Reproduce

1. Create new DT-inclusive structure via `php artisan enso:make:structure`
2. Add routes to `routes/api.php`
3. execute migrations
4. try to open the new menu

### Expected behavior

the page working

### Actual behavior

blank content; 500 error (route missing) when inspecting

**Comment by aocneanu** [comment] 2018-08-21 13:10
>When making breaking changes; ensure all sub-packages are updated before updating the Enso package.

Ok :) and what happens when / if we miss something?

>I based myself on a new clone of Enso this morning and it seems that structuremanager isn't/wasn't updated yet to reflect the dt changes (getting missing route errors; although the routes are defined in the same way that worked last week while playing around

Structure manager wasn't (now it is) updated to reflect the latest changes, indeed, but had nothing to do with routes. In addition, the extra attributes that needed to be removed from the stub files were very easy to detect by the table's template validator.

I'm not sure that I get the essence of this issue ;)

My team created today around 8 tables and they all worked seamless. 

If you can share some less abstract details about your issue I might be able to help

**Comment by jlsjonas** [comment] 2018-08-21 14:00
Very strange...

The issue (as explained) is that I'm just getting a blank page after generating a structure, and it can't find (at least) the destroy route (although it is declared in `routes/api.php` in the same way that worked last week)

I just generated a structure using all options & updated the table & model to reflect what I needed + copy/pasted the requested code at the bottom of api.php (last week I refactored it to be more cleanly contained in the already existent group; but I've tried without that step as well today but it can't seem to find the routes.


I just started from a clean slate again and had the same issue; but managed to solve it this time by fixing the declared `resource`: the resource key (attaching to the controller) uses the model name instead of the permission group tag that everything else uses

f.e.:
Given Permission group `administration.foo.bar` & model `FooBar`, the generated resource declaration becomes `Route::resource('foobar', 'FooBarController');` instead of `Route::resource('bar', 'FooBarController');`

p.s.: (this issue should likely be moved to StructureManager now that it's properly identified)

**Comment by aocneanu** [comment] 2018-08-22 05:56
>Given Permission group administration.foo.bar & model FooBar, the generated resource declaration becomes Route::resource('foobar', 'FooBarController'); instead of Route::resource('bar', 'FooBarController');

Actually from your example it seems that it works as intended.

The resource name, controller prefix, validator argument, table builder prefix, formbuilder prefix etc are all named after the model, not the last segment of the permission group.

Our convention is that the last segment of the permission group should be the camelcase version of the model. This way both the FE/BE routes look consistent, there no room for confusion.

The only thing I see wrong in your example is that if the model is named `FooBar` the resource should be `fooBar` instead of `foobar`. Are you sure you didn't made a typo there?

Maybe the documentation could be improved in this area, if so maybe you can make a contribution on that ;)

**Comment by jlsjonas** [comment] 2018-08-22 08:47
>Our convention is that the last segment of the permission group should be the camelcase version of the model. This way both the FE/BE routes look consistent, there no room for confusion.

This makes sense... unless you have a lot of items that belong together.
As Models (at least by default) go directly in `/app` a _prefixed_ model makes sense; no?

The way I see it:
I have several _structures_ to be created under `foo.`, i.e. `foo.bar`, `foo.baz`, ...
I don't want to call my permission groups `foo.foobar`, `foo.foobaz`, ... and it also doesn't seem to make a structural sense? 

In my opinion, as almost everything is based on the permission groups (routes etc.), it makes sense to use the last part of the permission group where it's _needed_ (the first parameter of the resource is tied to the route, and thus the permission group, after all)
(do correct me if I'm wrong).

as an aside: if that's the structure that StructureManager strictly assumes it should not ask for both parameters, but auto-concat them where required. (though I'd go for flexibility here, see above example.

**Comment by jlsjonas** [comment] 2018-08-22 11:56
🤔 the issue might be related to _multi-word_ models in general. the datatable was first erroring on the tablename (expecting `foo_bars` instead of `foobars`); however, the datatable helper seems to interpret it as `foobars.id as "dtRowId"`, causing an unknown column error

```
{
exception:"Illuminate\Database\QueryException",
file:"C:\Path\To\Project\vendor\laravel\framework\src\Illuminate\Database\Connection.php"
line:664,
message:"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'foobars.id' in 'field list' (SQL: select ↵            foobars.id as "dtRowId"↵         from `foo_bars` where `foo_bars`.`deleted_at` is null limit 10 offset 0)"
```

**Comment by aocneanu** [comment] 2018-08-22 12:02
>This makes sense... unless you have a lot of items that belong together.
As Models (at least by default) go directly in /app a prefixed model makes sense; no?

I would definitely go with subfolders in `app/models/`. We discussed about this internally and at some point we will make this move for Enso. When we will do that we will also update the structure manager.

>The way I see it:
I have several structures to be created under foo., i.e. foo.bar, foo.baz, ...
I don't want to call my permission groups foo.foobar, foo.foobaz, ... and it also doesn't seem to make a structural sense?

Taking this abstract example in consideration, why wouldn't you use `foo.bar` and `foo.baz` as permission groups and `Bar`, `Baz` as models?

Apparently the only problem is that you use FooBar, FooBaz as a model names. Out of curiosity, do you also have `foo_bars` and `foo_bazs` as tables? Or maybe you're using `protected $table="bar"` on the `FooBar model?

>In my opinion, as almost everything is based on the permission groups (routes etc.), it makes sense to use the last part of the permission group where it's needed (the first parameter of the resource is tied to the route, and thus the permission group, after all)
(do correct me if I'm wrong).

In my opinion having the last permission group segment different from the lowercase model and resource would only cause confusion. I would never expect that route(`myGroup.subGroup.cars.index`) would be anything else than the index for the `Car` model.

>as an aside: if that's the structure that StructureManager strictly assumes it should not ask for both parameters, but auto-concat them where required. (though I'd go for flexibility here, see above example.

Not really. you may have a `generic` group that can handle multiple structures..

> the issue might be related to multi-word models in general. the datatable was first erroring on the tablename (expecting foo_bars instead of foobars); however, the datatable helper seems to interpret it as foobars.id as "dtRowId", causing an unknown column error

What is `the datatable` helper? Also related to what the structure manager generates?

Anyway, this is turning into a general discussion on various topics on the wrong repo so I will close it now. 

If you want to do followups please open specific issues on the correct repo, and add a `#ref` to this issue too.

Thanks

**Closed by aocneanu** 2018-08-22 12:02 UTC

**Comment by jlsjonas** [comment] 2018-08-22 12:37
I agree the subfolder structure would work well from the code-perspective; however one of the main reasons to call the model `FooBar` instead of `Bar` nested in a `Foo` folder, is that you might have several models called `Bar` over time, but relating to different _subgroups_

Using `FooBar` as the model name allows those models to be (alphabetically) sorted next to each other + a convention-based tablename without risking collisions over time.

>I would never expect that route(myGroup.subGroup.cars.index) would be anything else than the index for the Car model.

Logically I believe it would still be clear if the model, in this case, would be `subGroupCar` instead (with the added benefit of being able to stick to convention-based table names.

**Comment by aocneanu** [comment] 2018-08-22 13:03
>Logically I believe it would still be clear if the model, in this case, would be subGroupCar

Then maybe an even more "logical" name should be `MyGroupSubGroupCar` ? :) Sorry, I don't see it that way.

**Comment by jlsjonas** [comment] 2018-08-22 13:17
Fair point...
It heavily depends on your use case I suppose....
f.e. for `administration.subGroup.cars` it doesn't make sense to have `Administration` as part of the name
for other cases it might be expected; which would make it a confusing feature 😅 

When dealing with a bigger application I do believe the "last" part of the permission group will likely also related to the model (simple example: it makes sense if given `car.parts` & `bike.parts` for it to become `CarPart` & `BikePart; but this won't always be the case ).
But I also agree that it's not always the case; and thus not suitable to be the convention

**Comment by jlsjonas** [comment] 2018-08-22 15:03
(for anyone stumbling upon this later on)

>The only thing I see wrong in your example is that if the model is named FooBar the resource should be fooBar instead of foobar. Are you sure you didn't made a typo there?

Looks like we both made a typo, it should've been `fooBars` (pluralized & lowerCamelCased)

So the convention is (example:
Model: `FooBar`
Permission group: `path.to.fooBars`
routes: `fooBars/*`
