### ISSUE TITLE
Calendar add not working

### ISSUE THREAD

**Issue by lsosa3** [laravel-enso/enso#228] opened 2019-05-22 03:08 UTC
This is  a **bug**.

### Prerequisites
* [*] Are you running the latest version?
* [*] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [*] Did you check the documentation?
* [*] Did you perform a cursory search?

### Description

Calendar add event not working
### Actual behavior

![Selección_069](https://user-images.githubusercontent.com/14814335/58144595-f7cf5780-7c1c-11e9-9a16-8110af7d600d.jpg)

Created the validateEventRequest.php file based on ValidateEventStore.php and then i get
this when i setup a reminder
![Selección_070](https://user-images.githubusercontent.com/14814335/58144667-5268b380-7c1d-11e9-811f-6cc9b9770ef9.png)

**Comment by heyner29** [comment] 2019-06-06 02:02
The problem is in the form requests that changed along with the sole responsibility.
You can follow the pull request that you opened while accepting it.
https://github.com/laravel-enso/calendar/pull/2

**Comment by aocneanu** [comment] 2019-06-12 05:22
fixed in the above PR

**Closed by aocneanu** 2019-06-12 05:22 UTC
