### ISSUE TITLE
I know this is a very open question but I am starting a new project and it will be in beta for awhile.  I wanted you opinion on whether to use 3.o to start since it will obviously be improved to start on 2 and upgrade later.  

### ISSUE THREAD

**Issue by ebgreen** [laravel-enso/Enso#205] opened 2019-03-17 03:48 UTC
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by jlsjonas** [comment] 2019-03-18 09:53
duplicate of #206

**Closed by jlsjonas** 2019-03-18 09:53 UTC
